### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nodeType')

### ISSUE THREAD

**Issue by oliwiaanna03** [Picodes/code4rena-report-generator#48]
I cloned the repository and navigated to the project folder. Upon installation of the package using `yarn`, I attempted to use a script using the command `yarn analyze contracts scope.example.txt`. However, I consistently encounter the following error:
```
Cannot compile AST for contracts/example/Test.sol
/github/xxx/node_modules/solidity-ast/utils/find-all.js:19
  const push = node => queue.push({ node, props: getNextProps(nodeType, node.nodeType ?? '$other', cache) });
                                                                             ^
TypeError: Cannot read properties of undefined (reading 'nodeType')
    at push (/github/xxx/node_modules/solidity-ast/utils/find-all.js:19:78)
    at findAll (/github/xxx/node_modules/solidity-ast/utils/find-all.js:21:3)
    at findAll.next (<anonymous>)
    at Object.detector (/github/xxx/src/issues/NC/uselessOverride.ts:15:18)
    at analyze (/github/xxx/src/analyze.ts:43:25)
    at main (/github/xxx/src/main.ts:69:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Of course for the purpose of anonimity I change my true path to `/github/xxx/`.

What should I do to use script? I use macbook and Visual Studio Code.

**Comment by igorbalden** [comment]
Same error in Ubuntu20. 
A quick fix is to go back one commit.
`$ git reset --hard HEAD~1`
or
`$ git reset --hard 098627c`

**Comment by devival** [comment]
The same error appears no matter the OS, going back one commit indeed helps but I'd also like to try the recent contributions by @JustDravee, 
Do you have any ideas on this?

**Comment by devival** [comment]
Removing `src/issues/NC/uselessOverride.ts` has worked for me.

**Comment by Top88Star** [comment]
> Removing `src/issues/NC/uselessOverride.ts` has worked for me.

Works for me too.
